Print (" Hello world ") 
Print (" today we starting a new project ") 
Print (" project.2.py") 
Print (" This project is based on python programming language ") 
Print (" Hello coders ") 
Print (" So, coders basically python programming language is easy language ") 
Print (" I have  a game for you ") 
Print (" A basic knowledge / age (game) ") 
Print ("let's start ") 
Print (" So coders what is your name ? ") 
Print (" Enter below ") 
Name = input (" What is your nick name??? ") 
Print ( " Hello" + name) 
Print (" So,what is your age ?") 
Print (" Enter below ") 
Current_age = input("enter your current age : ") 
New_age = int(old_age) + 2
Print (" So ") + name (" After two years your age will be this ") 
Print (new_age) 
Print ( "Is it true/false") 
True = input("I knew it") 
False = input(" I am solly  ") 
True or false = input(" Enter your answer true or false ") 
Print ("answer") 
Input (answer) 

